tomcat:
  image: zauxst/tomcat:0.4.2
  environment:
	- MANAGEMENT_ALLOW_REMOTE=FALSE
	- MANAGEMENT_USER=""
	- MANAGEMENT_PASSWORD=""
  ports:
  - "8080:8080"
  - "9009:8009"
  volumes:
  - "/srv/docker/tomcat/webapps/:/opt/tomcat/webapps/"
